version: "2"

services:

  app:
    build: ./
    volumes:
      - ./src:/opt/app/src
      - ./migrations:/opt/app/migrations
      - ./seeders:/opt/app/seeders
      - ./config:/opt/app/config
    environment:
      - AUTH0_SECRET=<change-me>
      - SLACK_WEBHOOK_URL=<change-me>
      - PORT=80
      - NODE_PATH=/opt/app
    command: >
      node_modules/.bin/nodemon src/index.js --exec "node -r dotenv/config -r babel-register"

  database:
    image: postgres:11
    environment:
      - POSTGRES_PASSWORD=<change-me>
